# Create Dataset: Combine Generated Synthetic Datasets with Real Datasets

1. **Synthetic:** generated with various LLMs across multiple domains (finance, weather, policy, health, sports, misc)
    1. DATASET: Predictions: future tense sentences + more.
    2. DATASET: Non-Predictions (or Observations): past tense sentences + more.
2. **Real:**
    1. DATASET: [financial_phrasebank](https://huggingface.co/datasets/takala/financial_phrasebank): 4840 statements (with sentiments) from financial calls, reports, news, etc

In [1]:
import os
import sys

import pandas as pd

from tqdm import tqdm

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

# import log_files
from data_processing import DataProcessing

In [ ]:
pd.set_option('max_colwidth', 800)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
save_data_bool = True

## Load Data

1. [x] Load Predictions
2. [x] Load Non-Predictions
3. [x] Load Financial PhraseBank

### Load Predictions

In [ ]:
predictions_df = DataProcessing.load_multiple_batches(
    notebook_dir,
    sep=',', 
    data_type='prediction'
)
predictions_df.head(7)

### Load Non-Predictions

In [ ]:
non_predictions_df = DataProcessing.load_multiple_batches(
    notebook_dir,
    sep=',', 
    data_type='observation'
)
non_predictions_df.head(7)

### Load financial_phrasebank

In [3]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
finacial_phrase_bank_path = os.path.join(base_data_path, 'financial_phrase_bank/annotators/maya_annotations-financial_phrasebank_statements-v3-final.csv')
print(finacial_phrase_bank_path)
finacial_phrase_bank_df = DataProcessing.load_from_file(finacial_phrase_bank_path, 'csv', sep = ",", encoding = 'latin')
finacial_phrase_bank_df.dropna(inplace=True) # drop rows without a lable
# fpb_label_values = finacial_phrase_bank_df['label_value'].values # convert to np.array
# fpb_label_values_updated = fpb_label_values.astype(int) # convert values to be type int
# finacial_phrase_bank_df['label_value'] = fpb_label_values_updated # update original df with type int
# finacial_phrase_bank_df.rename(columns={"sentence":"Base Sentence", "label_value":"Sentence Label"}, inplace=True)
# finacial_phrase_bank_df

finacial_phrase_bank_df

/Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/prediction_classification_experiments-v2/../data/financial_phrase_bank/annotators/maya_annotations-financial_phrasebank_statements-v3-final.csv

                                              statement      maya_label
1     According to Gran , the company has no plans t...  NON-PREDICTION
3     Technopolis plans to develop in stages an area...  NON-PREDICTION
5     The international electronic industry company ...  NON-PREDICTION
7     With the new production plant the company woul...      PREDICTION
9     According to the company 's updated strategy f...      PREDICTION
...                                                 ...             ...
9683  LONDON MarketWatch -- Share prices ended lower...  NON-PREDICTION
9685  Rinkuskiai 's beer sales fell by 6.5 per cent ...  NON-PREDICTION
9687  Operating profit fell to EUR 35.4 mn from EUR ...  NON-PREDICTION
9689  Net sales of the Paper segment decreased to EU...  NON-PREDICTION
9691  Sales in Finland decreased by 10.5 % in Januar...  NON-PREDICTION

[4846 rows x 2 columns]

In [4]:
# Using custom column name
updated_finacial_phrase_bank_df = DataProcessing.match_text_label_to_int(
    finacial_phrase_bank_df, 
    text_label_col_name='maya_label',
    target_label='PREDICTION'  # This is the default
)
updated_finacial_phrase_bank_df.rename(columns={"statement":"Base Sentence", "Binary Label":"Sentence Label"}, inplace=True)
updated_finacial_phrase_bank_df.head(3)

,Base Sentence,maya_label,Sentence Label
0,With the new production plant the company woul...,PREDICTION,1
1,According to the company 's updated strategy f...,PREDICTION,1
2,TeliaSonera TLSN said the offer is in line wit...,PREDICTION,1

## Data Processing

1. [x] Assign label 0 to LLM Generated for all Predictions
2. [x] Assign label 0 to LLM Generated for all Non-Predictions
3. [x] Assign label 1 to Human for financial_phrasebank and chronicles
4. [x] Filter for finance domain across Predictions
5. [x] Filter for finance domain across Non-Predictions
6. [x] Combine Predictions + Non-Predictions + financial_phrasebank + chronicles

In [5]:
llm_author_type = 0
human_author_type = 1

### Assign label 0 to LLM Generated for all Predictions

In [ ]:
predictions_df['Author Type'] = llm_author_type
predictions_df.head(3)

### Assign label 0 to LLM Generated for all Non-Predictions

In [ ]:
non_predictions_df['Author Type'] = llm_author_type
non_predictions_df.head(3)

### Assign label 1 to Human for financial_phrasebank

In [6]:
updated_finacial_phrase_bank_df['Author Type'] = human_author_type
updated_finacial_phrase_bank_df.head(3)

,Base Sentence,maya_label,Sentence Label,Author Type
0,With the new production plant the company woul...,PREDICTION,1,1
1,According to the company 's updated strategy f...,PREDICTION,1,1
2,TeliaSonera TLSN said the offer is in line wit...,PREDICTION,1,1

### Filter for finance domain across Predictions

In [ ]:
# filt_finance = (predictions_df['Domain'] == 'finance')
# financial_predictions_df = predictions_df[filt_finance]
# financial_predictions_df.head(3)

### Filter for finance domain across Non-Predictions

In [ ]:
# filt_finance = (non_predictions_df['Domain'] == 'finance')
# financial_non_predictions_df = non_predictions_df[filt_finance]
# financial_non_predictions_df.head(3)

### Combine Predictions + Non-Predictions + financial_phrasebank + chronicles

In [ ]:
joint_cols = ['Base Sentence', 'Sentence Label', 'Author Type']
# combined_df = DataProcessing.concat_dfs([financial_predictions_df, financial_non_predictions_df, updated_finacial_phrase_bank_df])
combined_df = DataProcessing.concat_dfs([predictions_df, non_predictions_df, updated_finacial_phrase_bank_df])

# combined_df.head(3)
basic_cols_df = combined_df.loc[: , joint_cols]
basic_cols_df.tail(7)

## Save Combined Dataset

In [7]:
if save_data_bool == True:
    # save_path = os.path.join(base_data_path, 'combined_datasets/')
    # DataProcessing.save_to_file(basic_cols_df, save_path, 'combined-synthetic-fin_phrase_bank', 'csv')

    save_path = os.path.join(base_data_path, 'financial_phrase_bank/annotators')
    DataProcessing.save_to_file(updated_finacial_phrase_bank_df, save_path, 'maya_annotations-fpb-binary_labels', 'csv')

Using file number: 2
Saving CSV file to: /Users/detraviousjamaribrinkley/Documents/Development/research_labs/uf_ds/predictions/prediction_classification_experiments-v2/../data/financial_phrase_bank/annotators/maya_annotations-fpb-binary_labels-v2.csv

- > `prediction_classification_experiments-v2/ml_classifiers.ipynb` to train ML models.
- > `notebook_experiments/imbalance_ex.ipynb` for ex of class imbalance, then can process to 1 to see in action.