# Label YouTube Text as either Prediction or Non-Prediction

- **Tasks:**
    1. Load YouTube transcripts extracted from `1-extract_transcripts.ipynb`.
    4. Clean the data.
    5. Create prompt to identify predictions.
    6. Pass each row of text + prompt into the [UF NaviGator Toolkit](https://it.ufl.edu/ai/navigator-toolkit/) or [Groq](https://console.groq.com/home) LLMs.
    7. Perform majority vote (MV) across all LLMs.
    8. Filter by MV label = 1, hence prediction.
    9. Verify that the text is/is not a prediction and update accordingly.

In [1]:
import os
import sys

import re
from typing import List

import pandas as pd
import numpy as np

from tqdm import tqdm
from youtube_transcript_api import YouTubeTranscriptApi

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))
# from metrics import Metrics
# from feature_extraction import SpacyFeatureExtraction
from data_processing import DataProcessing
from text_generation_models import TextGenerationModelFactory, llm_classify_text

In [2]:
pd.set_option('max_colwidth', 800)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

## Load Data

In [3]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
yt_data_path = os.path.join(base_data_path, 'yt', 'whisper_transcripts', 'sports')
transcripts = os.listdir(yt_data_path)

Choose the transcript video that you want to pass through the pipeline. 

Adjust the element from "transcripts" list to choose the right "Video ID".

In [4]:
transcript_path = os.path.join(yt_data_path, transcripts[2])

raw_transcripts_df = DataProcessing.load_from_file(path=transcript_path, file_type='csv')

raw_transcripts_df.head()

,Text,Start Time,Duration,Video ID
0,We have reached the end.,0.00,4.50,LXPQrZV4Cfw
1,One last game.,5.68,1.24,LXPQrZV4Cfw
2,"Patriots, Seahawks, Super Bowl 60 on Sunday in Santa Clara.",7.56,7.28,LXPQrZV4Cfw
3,A week from this Sunday.,14.84,1.30,LXPQrZV4Cfw
4,And how about the week that Kyle and Pete had?,16.14,3.08,LXPQrZV4Cfw

In [47]:
# dfs = []

# for transcript in tqdm(transcripts):
#     transcript_path = os.path.join(yt_data_path, transcript)
#     df = DataProcessing.load_from_file(path=transcript_path, file_type='csv')
#     dfs.append(df)

# raw_transcripts_df = DataProcessing.concat_dfs(dfs)
# raw_transcripts_df.head()

In [6]:
def clean_data(df) -> list[str]:
    """
    Split running text into sentence-like segments.
    Rules:
    - Split only where a period (.) or question mark (?) is immediately followed by
    whitespace. This avoids splitting decimals like ``4.5`` (digit after the dot,
    not a space).
    - Leading/trailing whitespace is stripped from each segment.
    - Empty segments are dropped.
    Caveat:
    - Abbreviations such as ``Mr. Smith`` still match ". " and may split incorrectly;
    handle those with a tokenizer or an allowlist if needed.
    Parameters
    ----------
    text : dataframe
        Full text to segment (e.g. one block of joined transcript lines).
    Returns
    -------
    list of str
        Non-empty strings, each intended as one sentence or clause.
    """

    text_joined = ' '.join(df.Text.to_list())
    raw_parts = re.split(r'(?<=[.?])\s+', text_joined)
    text_split = [p.strip() for p in raw_parts if p.strip()]

    return text_split

In [7]:
cleaned_transcripts = clean_data(raw_transcripts_df)
cleaned_transcripts

['We have reached the end.',
 'One last game.',
 'Patriots, Seahawks, Super Bowl 60 on Sunday in Santa Clara.',
 'A week from this Sunday.',
 'And how about the week that Kyle and Pete had?',
 'They both went 3-0.',
 'Both perfect conference championship.',
 'Great job, Pete.',
 'Best bets come through.',
 'Unreal.',
 'I got hot.',
 'Too late.',
 'Too little, too late.',
 'Yeah.',
 'Pete, the epic collapse is complete.',
 'Let me have my paper.',
 'I got something on the back of this paper.',
 'Look at Kyle in the postseason, 13-2 overall.',
 'You know what, man?',
 'You got to show up in the playoffs.',
 "And look, he's hit each of his last two best bets as well.",
 'That was what kind of strangled him in the regular season.',
 "He can't catch me with the best bets, so I have that going for me.",
 "It takes a while to figure out what we're looking at.",
 "I don't know if you can see this, but this says void.",
 'Yeah, it says void.',
 'You know why it says void?',
 'Why?',
 "We're voiding his title.",
 'Why?',
 "Because I've got sources that have explained to me that his little best bets props haven't been coming from him.",
 'Yes, they have.',
 "You've been accusing him of that the last few weeks.",
 "And that's okay.",
 'And I have a source on it.',
 'The truth will set you free.',
 'I have a source on it.',
 "So, basically, here's what happened with picks.",
 'He kind of finagled winning this one.',
 'And then on our picks on the site, Dave Richard changed like three picks on the last Sunday after the fact.',
 "See, that's cheating.",
 'And I called him out on it.',
 'He said, well, blah, blah, blah, blah, blah.',
 'Dave.',
 'Yeah.',
 'So the fact is I should be the winner of all of them.',
 'Okay.',
 'You all cheated me.',
 "Instead, you're the winner of none.",
 'None.',
 "I'm a loser.",
 'Absolutely nothing.',
 'All right.',
 'That was a collapse.',
 'Oh, that was a terrible collapse.',
 'Seahawks are a four and a half point favorite here, but underdogs have won the last three Super Bowls straight up.',
 "That's tied for the longest streak of all time.",
 "If the Patriots win this, it'll be the longest streak of all time.",
 "Well, they're not winning this one, the Patriots.",
 "And you know how I rank the rosters every year, one through 46 players, and I've been going through the rosters.",
 "I'm astounded that the New England Patriots are in the Super Bowl.",
 "I'll be honest with you.",
 'I really am.',
 'Have you released your player rankings yet?',
 'No, not yet.',
 'That comes out on Monday.',
 'So what are we looking at here?',
 'like eight of the top ten are Seahawks?',
 "No, not necessarily, but I just look at this team as a whole, and I don't see a lot of real top-tier talent on it, and that tells you that they're well coached in a lot of areas, particularly the head coach, but Josh McDaniels does a great job.",
 "They have a really good quarterback, but I just don't think the talent is great.",
 "You're an offensive line guy.",
 "These two teams don't have great offensive lines, neither one of them, and if you had to rank them, most people would rank the Patriots offensive line ahead of Seattle's offensive line.",
 "So it's just strange that we have two teams that are so not what you expect to be there in the Super Bowl.",
 "Good physical offensive lines and a lot of top tier talent because they don't, neither one of them really has it.",
 "So it's strange in the way that they kind of matched up.",
 "I'm glad you brought up Josh McDaniels because I feel like the top two priorities for Josh McDaniels having Drake May under center is protection and protection.",
 "If you watch him against the Broncos last week, Will Campbell was cutlocking front side about a dozen times, finding ways to get these defenders on the ground and the balls out quick, because to your point, they're not necessarily stalwarts up front.",
 'I think both coordinators have done a fantastic job playing to the strengths of the guys they have in their huddle.',
 'New England, they spread the football around, they protect Drake May, they run the football effectively.',
 "29 carries in the second half against the Denver Broncos, that's awesome.",
 'Bleed the whole clock out.',
 "You know what I'm saying?",
 'And for the Seattle Seahawks, they run the football to throw the football.',
 'They get Sam Darnold on the edges throwing it.',
 'They take shots down the field.',
 'Jackson Smith and Jigba is unguardable.',
 "I can't wait to watch this matchup.",
 "It's going to come down to both defenses.",
 "I think New England's defense will be the unit that wins or loses the game.",
 'You know, when I talk about ranking the players, we talk about offensive linemen.',
 "We go back to last year's Super Bowl.",
 'You had, you know, Milota and Lane Johnson were in the top 10.',
 'You had Creed Humphrey was in the top 10.',
 'And Trey Smith and Tooney are right behind that top 10.',
 'Now you go here and you look at these two offensive lines.',
 "Is there anybody who's a top 10 player on either line?",
 'No, I just think that the fact that they can rotate so many players on defense for both of these teams and so many guys are interchangeable.',
 "And to your point earlier about the Patriots, this reminds me of that kind of Patriots team where they are a team and they're well coached and they believe.",
 "And it's the new era of the Patriots.",
 "It's the same thing with the Seahawks.",
 "You're looking at a team that had like eight wins, nine wins.",
 'Now what are they, 14 wins?',
 'They have just gotten better and better.',
 'John Schneider has made all the right decisions.',
 'They got rid of Russell.',
 'They got rid of Geno.',
 'They got rid of DK.',
 "And I'm scratching my head.",
 'The rest of the hair I had on my head fell out.',
 'They brought in Cooper Cupp, and I was like, oh, this is not the solution.',
 'But then Jackson Smith and Jigma becomes JSN.',
 "And Sam Darnold shows us that he ain't going to become a pumpkin, One game left.",
 'One more chance.',
 'Both of these teams feel like teams of destiny, honestly.',
 "Like we've used that phrase a couple times in the playoffs.",
 'I mean, with that blizzard, the running game for New England, beating up on the Houston Texans defense, putting pressure on C.J.',
 'Stroud.',
 'Obviously they got a little help going against Stidham instead of Nix.',
 "It's going to be crazy.",
 'And the Seahawks had to earn it against the Rams.',
 'But no top ten offensive linemen.',
 'Seahawks had to earn it against the Rams.',
 'Different paths.',
 "It's incredible when you think about that.",
 'with the way the game is supposed to be played with a big physical, good offensive line with dominant players.',
 "They don't have them.",
 'Well, Pete clearly believes the Seahawks are the better team, will win this game, will cover.',
 'What do you think, Kyle?',
 'I also think that the Seattle Seahawks are to win this football game.',
 'I said at the beginning of the playoffs that Sam Darnold would host the Lombardi Trophy.',
 'I still fully believe that.',
 "It's all in the eyes, Chico.",
 "When I look at Sam Darnold's eyes right now, that's a man on an absolute mission.",
 'And behind him are some of the best 52 guys ready to roll in support of him.',
 "Yeah, I think they're a much better team.",
 "I think they're better.",
 "As good as New England has been on defense, I think the better defense is in Seattle, and I think offensively they're a better football team.",
 "But who's the best player on the field?",
 'Is it going to be Drake Mack?',
 "I mean, he's the guy that's in the running for MVP.",
 'I mean, he can be.',
 "He hasn't been in the playoffs.",
 'I mean, if you look at it.',
 "Yeah, the offense hasn't had to do a lot.",
 "But they haven't been very good in the playoffs, the offense.",
 "And he hasn't been great in the playoffs.",
 "He was good with his legs last week, but he wasn't great.",
 'Watch out for those guys on the defense for the Seattle Seahawks, particularly the guys on the line of scrimmage, guys like Nicky Manwari who can work his way into the box.',
 "He's done so much for the Seattle Seahawks defense.",
 'They have a pack of dogs on the Seahawks defense.',
 "To the defense of the Patriots, they'll say, well, yes, the Texans great on defense.",
 'The Broncos great on defense.',
 'We beat them both.',
 'Chargers good on defense.',
 'So what different challenges does the Seattle defense?',
 'They were at home for two of those games.',
 "That's a big difference.",
 'Both of the teams that they just beat had great guys on the edges.',
 "And it's easier to help with guys on the edges.",
 'Where are the issues for the Seattle Seahawks defense?',
 'Right there in front of your quarterback.',
 'Right down the barrel of the gun.',
 "So for Drake May, that's what it's going to be.",
 'His ability to get the football out on time.',
 'Those guards on the inside of a lackluster group.',
 'I mean, we saw it last week.',
 'That left side is going to need some help.',
 "And Garrett Bradbury, he's good at getting out to the second level.",
 "He's athletic.",
 'But you could put a big people on top of him and give him pushback.',
 "He's not a big center.",
 'And I think that could be a problem for them on the inside.',
 'In fact, I thought we were giving a prop out here as well.',
 'Leonard Williams over a half sack was one of my props.',
 'You can give a prop?',
 'Is that your prop?',
 "That's not my best bet, though.",
 'But you can give a prop.',
 "Well, there's a prop.",
 'Are you trying to give out several props so you can try to catch him?',
 "I'm going to catch him.",
 "I'll give him a prop, too.",
 'Next week.',
 'You can mathematically eliminate.',
 'No, not eliminate yet.',
 'if we give more props next week.',
 'Well, next week, yeah.',
 "We're going to be out there.",
 'We might as well have some game going.',
 'What do you think the vibe is going to be like for this?',
 'Because I talked to Kyle about this a little bit earlier on our YouTube piece.',
 "From the outside looking in, there's no Mahomes.",
 'So many years we had Brady in there.',
 'Blah.',
 'Yeah, it seems like that.',
 "Unless you're a football guy.",
 'Right.',
 "I mean, from a football standpoint, it's great.",
 'How do you sell it, though?',
 "It's going to be a hard sell.",
 "I think it's a hard sell.",
 "Let's just put it this way.",
 "It's a Paramount Plus movie and Sam Darnold, okay?",
 "It's the rookie of the second year, rookie of the year, Drake May, you know what I'm saying, who's almost the MVP.",
 'These are the new stars, right?',
 'Sam Darnold could be a guy we look back at four years from now, and he could have gone on a couple-year run with Seattle.',
 'But where are the villains?',
 'You know, you want villains.',
 'Mike Vrabel is kind of a villain.',
 "I think a lot of the country will find it easy to root against the Patriots just because of how often we've seen them in this situation over the last 20 years.",
 'Yeah, but the different team, though.',
 "It's a different team, and sometimes when you get removed from it, it's different.",
 "It's not Belichick.",
 "It's not Brady.",
 'So you look at it and you go, oh, new guys, Mike Vrabel and Drake May.',
 "We don't hate them as much, and I think there's some of that there.",
 "It is kind of a blah Super Bowl from the buildup and what people are saying about it Because you're right, there's no Mahomes, there's no Eagles going for another one.",
 'Back-to-back, Mahomes is going for three.',
 "There's no real, where are the villains?",
 'Every team has a villain.',
 'Where are the villains on these teams?',
 'Do you have any?',
 'For me, the villains are up front for the Seattle Seahawks.',
 "Well, they're nasty.",
 "They're nasty.",
 'The villains are up front for both defenses.',
 'But do they stand over toppy and taunt you and all that?',
 "No, they're extremely well coached.",
 'They respect the game of football.',
 "And I think that's why I enjoy watching these teams play.",
 'Because they fly around and they are taking on the identity of their coaches.',
 'The Mike and Mikes.',
 "You know what I'm saying?",
 "Mike McDonald's done a fantastic job with that group, the culture they've instilled.",
 "And I think they're no BS.",
 'They just go win.',
 "And the Patriots, we know how Vrabel's always been, and that's how his team is.",
 "But even Diggs, you know, in his past, he's not anymore.",
 "I mean, it's unbelievable.",
 'These teams are kind of dull.',
 'They still let Mac Hollins be Mac Hollins.',
 "They're damn good football teams, and that's all you want.",
 "But they're dull.",
 'All right, well, it sounds like you guys think the game might be dull, too, if the Seahawks are going to cover the four-and-a-half point spread.',
 "I think they'll cover the number, but I don't think it's going to be a violent, violent, nasty football.",
 "That's what you're going to get.",
 'All right.',
 'Super Bowl 60 is coming up a week from Sunday.',
 'We still have best bets.',
 'Wait a second.',
 'Why is Pete listed ahead of me?',
 'Wait a second.',
 'What is this crap?',
 'What did you do?',
 "I shouldn't be there.",
 'What did you do?',
 'Are we being DDoSed?',
 "I didn't do that.",
 "Unless somebody's giving you your picks, too.",
 "No, I'm the only one above 500.",
 "I'm listed second?",
 'Boyd, is somebody giving you your picks too?',
 "Since I'm number one, I'm going to give my first pick.",
 "And I'm going to go against you guys.",
 "I'm going to take the points with the Patriots.",
 'Patriots plus four and a half.',
 'Underdogs.',
 "I'm not saying they win it.",
 "You're going to lean into that.",
 'Underdogs, yes.',
 'Three straight times, the underdog has won outright.',
 'Five straight times, the underdog is covered in the Super Bowl.',
 "You're going with the pattern.",
 "I'm going to say six.",
 "You're staying.",
 "We're trend busters.",
 "That's what we need.",
 "We're on it.",
 'Give me some.',
 'Our last pick of the year.',
 'We buck trends.',
 'By the way, say that fast.',
 'By the way, say that fast.',
 'Bucking trends.',
 'Can we thank everybody for watching us and putting up with our BS all year?',
 'Absolutely.',
 'The last two years have been fun.',
 "It's great.",
 "As back-to-back champ, it's even more fun.",
 "Well, I mean, if I had people doing the work behind the scenes for me, I'd probably do it this season.",
 'Stop it.',
 'Kyle, what pick did they give you this week?',
 "This week, we're going pick for the game.",
 "I'm going to go Seattle Seahawks.",
 'My best bet is JSN anytime touchdown.',
 "If you watch the Seahawks, this guy's going to score.",
 "They're going to find a way.",
 'Who gave you that one?',
 'JSN.',
 'Me.',
 'Okay.',
 'You actually did that one this week?',
 'Mies Ohos.',
 "Because I know the last three you didn't do.",
 'I did.',
 'I did Jarrett Stidham rushing because I saw a graphic on TikTok that said Jarrett Stidham was a better dual threat quarterback than Lamar Jackson, Jawan Jennings, Joe Burrow.',
 'By the way, why was Joe Burrow even on that list?',
 'Whoever was evaluating dual threat or the definition of it should be fired.',
 'Joe Burrow, not a dual threat.',
 'When they came out of high school.',
 'Because Jawan Jennings was a quarterback.',
 'He was great.',
 'You want to give like five best bets so you can try to catch up here?',
 'No, I got one.',
 'Hunter Henry over 37 and a half receiving yards.',
 "You're going prop two?",
 'And you know why?',
 'Because the Seahawks all year have struggled against tight ends.',
 "And in the playoffs, they've given up, I think, 11 catches in the playoffs in their two games.",
 'And they average against them six and a half catches and 70 yards receiving from the tight end position.',
 "So that's going to be a problem.",
 'So that was your bonus one?',
 "That's my best bet.",
 "I'll give a bonus one.",
 'Okay.',
 "I'm going to go Tank Lawrence half a sack.",
 'I had Leonard Williams for half a sack.',
 "We're going to be in on it.",
 "I think we're both going to be right.",
 "They're going to be hugging Drake May together?",
 'No, no.',
 "They're each going to get more than a half.",
 "They're both going to get one.",
 'Great.',
 'There we go.',
 'We got one more best bet from the producers.',
 'I thought for sure it would be like a national anthem over under, something like that.',
 'There will be a falconer.',
 'Bad bunny number of dresses he wears at the halftime show.',
 "So they're going to go one rushing touchdown and one passing touchdown from each team.",
 'I like that.',
 'I like that.',
 'Some balance.',
 'We got some balance.',
 "And that's plus 220.",
 'So you got value on that.',
 'That is actually pretty good.',
 'We like value.',
 "Well, if you think it's going to be a defensive game, then maybe not so much.",
 'But I think I actually like that.',
 'These are the two.',
 'Not as unhinged as usual.',
 'When you combine regular season and postseason, And these are the two best defenses at not allowing points this season in the Patriots and the Seahawks.',
 "It's been fun.",
 'Those are our best bets for the final time.',
 'You guys are going to be out there.',
 "I'm sure you're going to give us a lot more picks coming up next week.",
 'And those will count, too.',
 'And then me and Pete go on vacation together.',
 'You know, they count.',
 'Going to Barbados together.',
 "We're going to Sandals.",
 "Let's make a decision.",
 'Should the picks we make out there count?',
 'Yes or no?',
 'Sure.',
 "Sure, they'll count.",
 "Yeah, let's count them.",
 'I can catch them then.',
 "We'll give you a shot, Pete.",
 "We'll give you a shot.",
 "I don't know.",
 "If his studio help gives him picks, I won't have a chance.",
 'Seahawks are looking to add to their Lombardi collection as they take on the Patriots in the big game.']

In [11]:
len(cleaned_transcripts)

374

## Prompt LLM

### Create Prompt

In [8]:
prompt = """
Role:
    You are a text analyst.

Task:
    Determine whether the input text contains a prediction, projection, or forecast.

Definitions:
    - A prediction is a statement that asserts or implies a future outcome, result, or event.
    - It may include confidence, uncertainty, or probability.
    - It must go beyond describing current or past facts.

Instructions:
    1. Read the text carefully.
    2. Decide if a prediction/projection/forecast is present.
    3. Assign:
        - 1 if a prediction is present
        - 0 if no prediction is present

Output format (strict JSON):
    {
        "label": 0 or 1
    }
"""

### Initialize LLMs

In [9]:
tgmf = TextGenerationModelFactory()

# Option 3: All NaviGator models
# models = tgmf.create_instances(tgmf.get_navigator_model_names())
models = tgmf.create_instances(['llama-3.1-8b-instant', 'llama-3.3-70b-versatile', 'openai/gpt-oss-120b'])
models

{'llama-3.1-8b-instant': <text_generation_models.LlamaInstantTextGenerationModel at 0x26ebf8bee10>,
 'llama-3.3-70b-versatile': <text_generation_models.LlamaVersatileTextGenerationModel at 0x26ebf963490>,
 'openai/gpt-oss-120b': <text_generation_models.GptOss120bTextGenerationModel at 0x26ebf8bd850>}

### Pass data + prompt into each LLM

In [10]:
results = []
PROMPT_TYPE = "zero-shot"   # change to "chain-of-thought" when needed

for cleaned_transcript_idx in range(len(cleaned_transcripts)):
    text = cleaned_transcripts[cleaned_transcript_idx]
    print(f"{cleaned_transcript_idx} --- Sentence: {text}")

    for model_name, model in models.items():
        raw_response, llm_label, llm_reasoning = llm_classify_text(
            data=text,
            base_prompt=prompt,
            prompt_type=PROMPT_TYPE,
            model=model
        )

        result = (
            text,
            raw_response,
            llm_label,
            llm_reasoning,
            model_name
        )
        results.append(result)

        if cleaned_transcript_idx < 3:
            if PROMPT_TYPE == "chain-of-thought":
                print(
                    f" Model: {model_name} "
                    f"| Label: {llm_label} "
                    f"| Reasoning: {llm_reasoning}"
                )
            else:
                print(
                    f" Model: {model_name} "
                    f"| Label: {llm_label}"
                )

0 --- Sentence: We have reached the end.
 Model: llama-3.1-8b-instant | Label: 0
 Model: llama-3.3-70b-versatile | Label: 0
 Model: openai/gpt-oss-120b | Label: 0
1 --- Sentence: One last game.
 Model: llama-3.1-8b-instant | Label: 0
 Model: llama-3.3-70b-versatile | Label: 0
 Model: openai/gpt-oss-120b | Label: 1
2 --- Sentence: Patriots, Seahawks, Super Bowl 60 on Sunday in Santa Clara.
 Model: llama-3.1-8b-instant | Label: 0
 Model: llama-3.3-70b-versatile | Label: 1
 Model: openai/gpt-oss-120b | Label: 1
3 --- Sentence: A week from this Sunday.
4 --- Sentence: And how about the week that Kyle and Pete had?
5 --- Sentence: They both went 3-0.
6 --- Sentence: Both perfect conference championship.
7 --- Sentence: Great job, Pete.
8 --- Sentence: Best bets come through.
9 --- Sentence: Unreal.
10 --- Sentence: I got hot.
11 --- Sentence: Too late.
12 --- Sentence: Too little, too late.
13 --- Sentence: Yeah.
14 --- Sentence: Pete, the epic collapse is complete.
15 --- Sentence: Let me have my paper.
16 --- Sentence: I got something on the back of this paper.
17 --- Sentence: Look at Kyle in the postseason, 13-2 overall.
18 --- Sentence: You know what, man?
19 --- Sentence: You got to show up in the playoffs.
20 --- Sentence: And look, he's hit each of his last two best bets as well.
21 --- Sentence: That was what kind of strangled him in the regular season.
22 --- Sentence: He can't catch me with the best bets, so I have that going for me.
23 --- Sentence: It takes a while to figure out what we're looking at.
24 --- Sentence: I don't know if you can see this, but this says void.
25 --- Sentence: Yeah, it says void.
26 --- Sentence: You know why it says void?
27 --- Sentence: Why?
28 --- Sentence: We're voiding his title.
29 --- Sentence: Why?
30 --- Sentence: Because I've got sources that have explained to me that his little best bets props haven't been coming from him.
31 --- Sentence: Yes, they have.
32 --- Sentence: You've been accusing him of that the last few weeks.
33 --- Sentence: And that's okay.
34 --- Sentence: And I have a source on it.
35 --- Sentence: The truth will set you free.
36 --- Sentence: I have a source on it.
37 --- Sentence: So, basically, here's what happened with picks.
38 --- Sentence: He kind of finagled winning this one.
39 --- Sentence: And then on our picks on the site, Dave Richard changed like three picks on the last Sunday after the fact.
40 --- Sentence: See, that's cheating.
41 --- Sentence: And I called him out on it.
42 --- Sentence: He said, well, blah, blah, blah, blah, blah.
43 --- Sentence: Dave.
44 --- Sentence: Yeah.
45 --- Sentence: So the fact is I should be the winner of all of them.
46 --- Sentence: Okay.
47 --- Sentence: You all cheated me.
48 --- Sentence: Instead, you're the winner of none.
49 --- Sentence: None.
50 --- Sentence: I'm a loser.
51 --- Sentence: Absolutely nothing.
52 --- Sentence: All right.
53 --- Sentence: That was a collapse.
54 --- Sentence: Oh, that was a terrible collapse.
55 --- Sentence: Seahawks are a four and a half point favorite here, but underdogs have won the last three Super Bowls straight up.
56 --- Sentence: That's tied for the longest streak of all time.
57 --- Sentence: If the Patriots win this, it'll be the longest streak of all time.
58 --- Sentence: Well, they're not winning this one, the Patriots.
59 --- Sentence: And you know how I rank the rosters every year, one through 46 players, and I've been going through the rosters.
60 --- Sentence: I'm astounded that the New England Patriots are in the Super Bowl.
61 --- Sentence: I'll be honest with you.
62 --- Sentence: I really am.
63 --- Sentence: Have you released your player rankings yet?
64 --- Sentence: No, not yet.
65 --- Sentence: That comes out on Monday.
66 --- Sentence: So what are we looking at here?
67 --- Sentence: like eight of the top ten are Seahawks?
68 --- Sentence: No, not necessarily, but I just look at this team as a whole, and I don't see a lot of real top-tier talent on it, and that tells you that they're well coached in a lot of areas, particularly the head coach, but Josh McDaniels does a great job.
69 --- Sentence: They have a really good quarterback, but I just don't think the talent is great.
70 --- Sentence: You're an offensive line guy.
71 --- Sentence: These two teams don't have great offensive lines, neither one of them, and if you had to rank them, most people would rank the Patriots offensive line ahead of Seattle's offensive line.
72 --- Sentence: So it's just strange that we have two teams that are so not what you expect to be there in the Super Bowl.
73 --- Sentence: Good physical offensive lines and a lot of top tier talent because they don't, neither one of them really has it.
74 --- Sentence: So it's strange in the way that they kind of matched up.
75 --- Sentence: I'm glad you brought up Josh McDaniels because I feel like the top two priorities for Josh McDaniels having Drake May under center is protection and protection.
76 --- Sentence: If you watch him against the Broncos last week, Will Campbell was cutlocking front side about a dozen times, finding ways to get these defenders on the ground and the balls out quick, because to your point, they're not necessarily stalwarts up front.
77 --- Sentence: I think both coordinators have done a fantastic job playing to the strengths of the guys they have in their huddle.
78 --- Sentence: New England, they spread the football around, they protect Drake May, they run the football effectively.
79 --- Sentence: 29 carries in the second half against the Denver Broncos, that's awesome.
80 --- Sentence: Bleed the whole clock out.
81 --- Sentence: You know what I'm saying?
82 --- Sentence: And for the Seattle Seahawks, they run the football to throw the football.
83 --- Sentence: They get Sam Darnold on the edges throwing it.
84 --- Sentence: They take shots down the field.
85 --- Sentence: Jackson Smith and Jigba is unguardable.
86 --- Sentence: I can't wait to watch this matchup.
87 --- Sentence: It's going to come down to both defenses.
88 --- Sentence: I think New England's defense will be the unit that wins or loses the game.
89 --- Sentence: You know, when I talk about ranking the players, we talk about offensive linemen.
90 --- Sentence: We go back to last year's Super Bowl.
91 --- Sentence: You had, you know, Milota and Lane Johnson were in the top 10.
92 --- Sentence: You had Creed Humphrey was in the top 10.
93 --- Sentence: And Trey Smith and Tooney are right behind that top 10.
94 --- Sentence: Now you go here and you look at these two offensive lines.
95 --- Sentence: Is there anybody who's a top 10 player on either line?
96 --- Sentence: No, I just think that the fact that they can rotate so many players on defense for both of these teams and so many guys are interchangeable.
97 --- Sentence: And to your point earlier about the Patriots, this reminds me of that kind of Patriots team where they are a team and they're well coached and they believe.
98 --- Sentence: And it's the new era of the Patriots.
99 --- Sentence: It's the same thing with the Seahawks.
100 --- Sentence: You're looking at a team that had like eight wins, nine wins.
101 --- Sentence: Now what are they, 14 wins?
102 --- Sentence: They have just gotten better and better.
103 --- Sentence: John Schneider has made all the right decisions.
104 --- Sentence: They got rid of Russell.
105 --- Sentence: They got rid of Geno.
106 --- Sentence: They got rid of DK.
107 --- Sentence: And I'm scratching my head.
108 --- Sentence: The rest of the hair I had on my head fell out.
109 --- Sentence: They brought in Cooper Cupp, and I was like, oh, this is not the solution.
110 --- Sentence: But then Jackson Smith and Jigma becomes JSN.
111 --- Sentence: And Sam Darnold shows us that he ain't going to become a pumpkin, One game left.
112 --- Sentence: One more chance.
113 --- Sentence: Both of these teams feel like teams of destiny, honestly.
114 --- Sentence: Like we've used that phrase a couple times in the playoffs.
115 --- Sentence: I mean, with that blizzard, the running game for New England, beating up on the Houston Texans defense, putting pressure on C.J.
116 --- Sentence: Stroud.
117 --- Sentence: Obviously they got a little help going against Stidham instead of Nix.
118 --- Sentence: It's going to be crazy.
119 --- Sentence: And the Seahawks had to earn it against the Rams.
120 --- Sentence: But no top ten offensive linemen.
121 --- Sentence: Seahawks had to earn it against the Rams.
122 --- Sentence: Different paths.
123 --- Sentence: It's incredible when you think about that.
124 --- Sentence: with the way the game is supposed to be played with a big physical, good offensive line with dominant players.
125 --- Sentence: They don't have them.
126 --- Sentence: Well, Pete clearly believes the Seahawks are the better team, will win this game, will cover.
127 --- Sentence: What do you think, Kyle?
128 --- Sentence: I also think that the Seattle Seahawks are to win this football game.
129 --- Sentence: I said at the beginning of the playoffs that Sam Darnold would host the Lombardi Trophy.
130 --- Sentence: I still fully believe that.
131 --- Sentence: It's all in the eyes, Chico.
132 --- Sentence: When I look at Sam Darnold's eyes right now, that's a man on an absolute mission.
133 --- Sentence: And behind him are some of the best 52 guys ready to roll in support of him.
134 --- Sentence: Yeah, I think they're a much better team.
135 --- Sentence: I think they're better.
136 --- Sentence: As good as New England has been on defense, I think the better defense is in Seattle, and I think offensively they're a better football team.
137 --- Sentence: But who's the best player on the field?
138 --- Sentence: Is it going to be Drake Mack?
139 --- Sentence: I mean, he's the guy that's in the running for MVP.
140 --- Sentence: I mean, he can be.
141 --- Sentence: He hasn't been in the playoffs.
142 --- Sentence: I mean, if you look at it.
143 --- Sentence: Yeah, the offense hasn't had to do a lot.
144 --- Sentence: But they haven't been very good in the playoffs, the offense.
145 --- Sentence: And he hasn't been great in the playoffs.
146 --- Sentence: He was good with his legs last week, but he wasn't great.
147 --- Sentence: Watch out for those guys on the defense for the Seattle Seahawks, particularly the guys on the line of scrimmage, guys like Nicky Manwari who can work his way into the box.
148 --- Sentence: He's done so much for the Seattle Seahawks defense.
149 --- Sentence: They have a pack of dogs on the Seahawks defense.
150 --- Sentence: To the defense of the Patriots, they'll say, well, yes, the Texans great on defense.
151 --- Sentence: The Broncos great on defense.
152 --- Sentence: We beat them both.
153 --- Sentence: Chargers good on defense.
154 --- Sentence: So what different challenges does the Seattle defense?
155 --- Sentence: They were at home for two of those games.
156 --- Sentence: That's a big difference.
157 --- Sentence: Both of the teams that they just beat had great guys on the edges.
158 --- Sentence: And it's easier to help with guys on the edges.
159 --- Sentence: Where are the issues for the Seattle Seahawks defense?
160 --- Sentence: Right there in front of your quarterback.
161 --- Sentence: Right down the barrel of the gun.
162 --- Sentence: So for Drake May, that's what it's going to be.
163 --- Sentence: His ability to get the football out on time.
164 --- Sentence: Those guards on the inside of a lackluster group.
165 --- Sentence: I mean, we saw it last week.
166 --- Sentence: That left side is going to need some help.
167 --- Sentence: And Garrett Bradbury, he's good at getting out to the second level.
168 --- Sentence: He's athletic.
169 --- Sentence: But you could put a big people on top of him and give him pushback.
170 --- Sentence: He's not a big center.
171 --- Sentence: And I think that could be a problem for them on the inside.
172 --- Sentence: In fact, I thought we were giving a prop out here as well.
173 --- Sentence: Leonard Williams over a half sack was one of my props.
174 --- Sentence: You can give a prop?
175 --- Sentence: Is that your prop?
176 --- Sentence: That's not my best bet, though.
177 --- Sentence: But you can give a prop.
178 --- Sentence: Well, there's a prop.
179 --- Sentence: Are you trying to give out several props so you can try to catch him?
180 --- Sentence: I'm going to catch him.
181 --- Sentence: I'll give him a prop, too.
182 --- Sentence: Next week.
183 --- Sentence: You can mathematically eliminate.
184 --- Sentence: No, not eliminate yet.
185 --- Sentence: if we give more props next week.
186 --- Sentence: Well, next week, yeah.
187 --- Sentence: We're going to be out there.
188 --- Sentence: We might as well have some game going.
189 --- Sentence: What do you think the vibe is going to be like for this?
190 --- Sentence: Because I talked to Kyle about this a little bit earlier on our YouTube piece.
191 --- Sentence: From the outside looking in, there's no Mahomes.
192 --- Sentence: So many years we had Brady in there.
193 --- Sentence: Blah.
194 --- Sentence: Yeah, it seems like that.
195 --- Sentence: Unless you're a football guy.
196 --- Sentence: Right.
197 --- Sentence: I mean, from a football standpoint, it's great.
198 --- Sentence: How do you sell it, though?
199 --- Sentence: It's going to be a hard sell.
200 --- Sentence: I think it's a hard sell.
201 --- Sentence: Let's just put it this way.
202 --- Sentence: It's a Paramount Plus movie and Sam Darnold, okay?
203 --- Sentence: It's the rookie of the second year, rookie of the year, Drake May, you know what I'm saying, who's almost the MVP.
204 --- Sentence: These are the new stars, right?
205 --- Sentence: Sam Darnold could be a guy we look back at four years from now, and he could have gone on a couple-year run with Seattle.
206 --- Sentence: But where are the villains?
207 --- Sentence: You know, you want villains.
208 --- Sentence: Mike Vrabel is kind of a villain.
209 --- Sentence: I think a lot of the country will find it easy to root against the Patriots just because of how often we've seen them in this situation over the last 20 years.
210 --- Sentence: Yeah, but the different team, though.
211 --- Sentence: It's a different team, and sometimes when you get removed from it, it's different.
212 --- Sentence: It's not Belichick.
213 --- Sentence: It's not Brady.
214 --- Sentence: So you look at it and you go, oh, new guys, Mike Vrabel and Drake May.
215 --- Sentence: We don't hate them as much, and I think there's some of that there.
216 --- Sentence: It is kind of a blah Super Bowl from the buildup and what people are saying about it Because you're right, there's no Mahomes, there's no Eagles going for another one.
217 --- Sentence: Back-to-back, Mahomes is going for three.
218 --- Sentence: There's no real, where are the villains?
219 --- Sentence: Every team has a villain.
220 --- Sentence: Where are the villains on these teams?
221 --- Sentence: Do you have any?
222 --- Sentence: For me, the villains are up front for the Seattle Seahawks.
223 --- Sentence: Well, they're nasty.
224 --- Sentence: They're nasty.
225 --- Sentence: The villains are up front for both defenses.
226 --- Sentence: But do they stand over toppy and taunt you and all that?
227 --- Sentence: No, they're extremely well coached.
228 --- Sentence: They respect the game of football.
229 --- Sentence: And I think that's why I enjoy watching these teams play.
230 --- Sentence: Because they fly around and they are taking on the identity of their coaches.
231 --- Sentence: The Mike and Mikes.
232 --- Sentence: You know what I'm saying?
233 --- Sentence: Mike McDonald's done a fantastic job with that group, the culture they've instilled.
234 --- Sentence: And I think they're no BS.
235 --- Sentence: They just go win.
236 --- Sentence: And the Patriots, we know how Vrabel's always been, and that's how his team is.
237 --- Sentence: But even Diggs, you know, in his past, he's not anymore.
238 --- Sentence: I mean, it's unbelievable.
239 --- Sentence: These teams are kind of dull.
240 --- Sentence: They still let Mac Hollins be Mac Hollins.
241 --- Sentence: They're damn good football teams, and that's all you want.
242 --- Sentence: But they're dull.
243 --- Sentence: All right, well, it sounds like you guys think the game might be dull, too, if the Seahawks are going to cover the four-and-a-half point spread.
244 --- Sentence: I think they'll cover the number, but I don't think it's going to be a violent, violent, nasty football.
245 --- Sentence: That's what you're going to get.
246 --- Sentence: All right.
247 --- Sentence: Super Bowl 60 is coming up a week from Sunday.
248 --- Sentence: We still have best bets.
249 --- Sentence: Wait a second.
250 --- Sentence: Why is Pete listed ahead of me?
251 --- Sentence: Wait a second.
252 --- Sentence: What is this crap?
253 --- Sentence: What did you do?
254 --- Sentence: I shouldn't be there.
255 --- Sentence: What did you do?
256 --- Sentence: Are we being DDoSed?
257 --- Sentence: I didn't do that.
258 --- Sentence: Unless somebody's giving you your picks, too.
259 --- Sentence: No, I'm the only one above 500.
260 --- Sentence: I'm listed second?
261 --- Sentence: Boyd, is somebody giving you your picks too?
262 --- Sentence: Since I'm number one, I'm going to give my first pick.
263 --- Sentence: And I'm going to go against you guys.
264 --- Sentence: I'm going to take the points with the Patriots.
265 --- Sentence: Patriots plus four and a half.
266 --- Sentence: Underdogs.
267 --- Sentence: I'm not saying they win it.
268 --- Sentence: You're going to lean into that.
269 --- Sentence: Underdogs, yes.
270 --- Sentence: Three straight times, the underdog has won outright.
271 --- Sentence: Five straight times, the underdog is covered in the Super Bowl.
272 --- Sentence: You're going with the pattern.
273 --- Sentence: I'm going to say six.
274 --- Sentence: You're staying.
275 --- Sentence: We're trend busters.
276 --- Sentence: That's what we need.
277 --- Sentence: We're on it.
278 --- Sentence: Give me some.
279 --- Sentence: Our last pick of the year.
280 --- Sentence: We buck trends.
281 --- Sentence: By the way, say that fast.
282 --- Sentence: By the way, say that fast.
283 --- Sentence: Bucking trends.
284 --- Sentence: Can we thank everybody for watching us and putting up with our BS all year?
285 --- Sentence: Absolutely.
286 --- Sentence: The last two years have been fun.
287 --- Sentence: It's great.
288 --- Sentence: As back-to-back champ, it's even more fun.
289 --- Sentence: Well, I mean, if I had people doing the work behind the scenes for me, I'd probably do it this season.
290 --- Sentence: Stop it.
291 --- Sentence: Kyle, what pick did they give you this week?
292 --- Sentence: This week, we're going pick for the game.
293 --- Sentence: I'm going to go Seattle Seahawks.
294 --- Sentence: My best bet is JSN anytime touchdown.
295 --- Sentence: If you watch the Seahawks, this guy's going to score.
296 --- Sentence: They're going to find a way.
297 --- Sentence: Who gave you that one?
298 --- Sentence: JSN.
299 --- Sentence: Me.
300 --- Sentence: Okay.
301 --- Sentence: You actually did that one this week?
302 --- Sentence: Mies Ohos.

RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kbn2rg8gf1jax2p86k7vdraq` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99977, Requested 220. Please try again in 2m50.208s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

> - DataFrame below will have the same sentence (in text column) for all three llms (in the llm_name), then next set of rows will be another sentences with same llms.
> - llm_label column: {0: non-prediction, 1: prediction}

In [11]:
results_with_llm_label_df = pd.DataFrame(
    results,
    columns=['text', 'raw_response', 'llm_label', 'llm_reasoning', 'llm_name']
)

# Ensure labels are valid integers (0/1), fallback to -1 if malformed
results_with_llm_label_df['llm_label'] = (
    pd.to_numeric(results_with_llm_label_df['llm_label'], errors='coerce')
      .fillna(-1)
      .astype(int)
)

# Normalize reasoning: keep only when present (chain-of-thought), else None
results_with_llm_label_df['llm_reasoning'] = (
    results_with_llm_label_df['llm_reasoning'].where(
        results_with_llm_label_df['llm_reasoning'].notna(),
        None
    )
)

results_with_llm_label_df.tail(6)

,text,raw_response,llm_label,llm_reasoning,llm_name
273,"Hey, you made it all the way to the end.","{""label"": 0}",0,None,llama-3.1-8b-instant
274,"Hey, you made it all the way to the end.","{""label"": 0}",0,None,llama-3.3-70b-versatile
275,"Hey, you made it all the way to the end.","{""label"": 0}",0,None,openai/gpt-oss-120b
276,Thanks for that.,"{""label"": 0}",0,None,llama-3.1-8b-instant
277,Thanks for that.,"{""label"": 0}",0,None,llama-3.3-70b-versatile
278,Thanks for that.,"{""label"": 0}",0,None,openai/gpt-oss-120b

In [12]:
# Reshape to have llm names as column names
results_df = (
    results_with_llm_label_df
    .pivot_table(
        index='text',
        columns='llm_name',
        values='llm_label',
        aggfunc='first'   # one label per model per sentence
    )
    .reset_index()
    .rename(columns={'text': 'Base Sentence'})
)
results_df

llm_name,Base Sentence,llama-3.1-8b-instant,llama-3.3-70b-versatile,openai/gpt-oss-120b
0,And I can't wait to hear from all of you.,0,0,0
1,And I find it ironic that Adam Vinatieri was inducted into the Pro Football Hall of Fame.,0,0,0
2,And I think Seattle fans will be very happy.,1,1,1
3,And I want an MVP on top of it.,0,0,0
4,And I've been running an okey-doke week after week after week.,0,0,0
...,...,...,...,...
84,Yeah.,0,0,0
85,You both are big defensive MVPs.,0,0,0
86,You don't even get to score.,0,0,0
87,came down to a field goal by Adam Vinatieri to win that Super Bowl.,0,0,0
88,the Pats go up 23 to 20.,1,0,0

### Majority Vote (across LLMs)

> - llm_label column: {0: non-prediction, 1: prediction}

In [13]:
results_df['Majority Vote Label'] = (
    results_df
    .iloc[:, 1:]               # exclude sentence column
    .mode(axis=1)[0]
    .astype(int)
)

results_df.head()

llm_name,Base Sentence,llama-3.1-8b-instant,llama-3.3-70b-versatile,openai/gpt-oss-120b,Majority Vote Label
0,And I can't wait to hear from all of you.,0,0,0,0
1,And I find it ironic that Adam Vinatieri was inducted into the Pro Football Hall of Fame.,0,0,0,0
2,And I think Seattle fans will be very happy.,1,1,1,1
3,And I want an MVP on top of it.,0,0,0,0
4,And I've been running an okey-doke week after week after week.,0,0,0,0

Add 'Human Annotation', 'Human Reasoning' columns to write human input, and 'Video ID' column to grab the video source from the respective sentence.

In [14]:
results_df[['Human Annotation', 'Human Reasoning']] = np.nan
final_results_df = pd.concat([results_df, raw_transcripts_df[['Video ID']]], axis=1)
final_results_df.head()

,Base Sentence,llama-3.1-8b-instant,llama-3.3-70b-versatile,openai/gpt-oss-120b,Majority Vote Label,Human Annotation,Human Reasoning,Video ID
0,And I can't wait to hear from all of you.,0.0,0.0,0.0,0.0,NaN,NaN,fUmJAtFEGn8
1,And I find it ironic that Adam Vinatieri was inducted into the Pro Football Hall of Fame.,0.0,0.0,0.0,0.0,NaN,NaN,fUmJAtFEGn8
2,And I think Seattle fans will be very happy.,1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
3,And I want an MVP on top of it.,0.0,0.0,0.0,0.0,NaN,NaN,fUmJAtFEGn8
4,And I've been running an okey-doke week after week after week.,0.0,0.0,0.0,0.0,NaN,NaN,fUmJAtFEGn8

In [15]:
predictions = final_results_df[final_results_df['Majority Vote Label']==1]

In [16]:
predictions

,Base Sentence,llama-3.1-8b-instant,llama-3.3-70b-versatile,openai/gpt-oss-120b,Majority Vote Label,Human Annotation,Human Reasoning,Video ID
2,And I think Seattle fans will be very happy.,1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
5,"And at the end of the day, Super Bowl 60 is going to be won by the Seattle Seahawks.",1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
6,"And he has been vocal quite a bit about Seattle being able to lay in wait and destroy teams, and that's where I'm going.",1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
7,And it's going to be a 24-10 victory for the Seattle Seahawks.,1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
8,And that's my prediction for Super Bowl 60 in advance.,1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
11,And their defense is going to do it.,1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
12,"And they are going to get the defensive stops, 24-10.",1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
13,"And your Super Bowl MVP will be Demarcus Lawrence, baby.",1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
17,But this is going to come down to an Andy Borogalis game-winning field goal.,1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
34,I give them maybe 23-20.,1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
38,I say it's going to be probably low in the 20s.,1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
40,"I think the Pats are going to wind up, and I'm a little higher ready, I think the Pats got this one.",1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
41,"I'm going the Seattle Seahawks win Super Bowl 60 by two touchdowns, which is a rarity for these two teams to play a game that's got a margin of victory more than just a touchdown, and I think the defense will lead them.",1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
42,"I'm going to peg him as the guy who is going to come up with some sacks and maybe a sack force fumble, and the Seahawks are going to get this thing done.",1.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
45,It is now time for us to predict Super Bowl 60.,1.0,1.0,0.0,1.0,NaN,NaN,fUmJAtFEGn8
71,They're going to get a little bit of here in the offense.,0.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8
72,They're going to get a little bit of there in special teams.,0.0,1.0,1.0,1.0,NaN,NaN,fUmJAtFEGn8

In [17]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir=notebook_dir)
save_data_path = os.path.join(base_data_path, "yt", "majority_vote", "sports")
DataProcessing.save_to_file(predictions, path=save_data_path, prefix='batch_2', save_file_type='csv', include_version=False)

Saving CSV file to: c:\Users\adria\OneDrive\Área de Trabalho\UF Data Studio\predictions\prediction_acquition-youtube\../data\yt\majority_vote\sports\batch_2.csv